"""
utils/file_exporter.py
-----------------------
Builds and serialises the two output formats: .docx and .txt.
Also provides helpers to read file bytes for Supabase Storage upload.

python-docx is used for .docx generation.
Plain file I/O is used for .txt generation.
No third-party PDF or conversion libraries are used.
"""

import io
import logging
from pathlib import Path

from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH

log = logging.getLogger(__name__)


class ExportError(Exception):
    """Raised when file building or I/O fails during export."""


def _clean_markdown(text: str) -> str:
    """
    Strip AI-generated Markdown tokens from the text to make it clean for Word/TXT.
    """
    if not text:
        return ""
    import re
    # Remove # headers
    text = re.sub(r'^#+\s*', '', text, flags=re.MULTILINE)
    # Remove bold/italic markers (**text**, *text*, __text__, _text_)
    text = re.sub(r'\*\*+(.*?)\*\*+', r'\1', text)
    text = re.sub(r'\*(.*?)\*', r'\1', text)
    text = re.sub(r'__+(.*?)__+', r'\1', text)
    text = re.sub(r'_(.*?)_', r'\1', text)
    # Remove excessive empty lines
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()


# ── .docx Builder ─────────────────────────────────────────────────────────────

def build_docx(title: str, chapters: list[dict]) -> bytes:
    """
    Assemble a .docx document with a title page, static TOC, and chapter content.

    Args:
        title:    The book title (used on the title page and TOC header).
        chapters: List of chapter dicts, each containing:
                    chapter_number (int), title (str), content (str).
                  (Automatically sorted by chapter_number if not already).

    Returns:
        Raw bytes of the compiled .docx file.

    Raises:
        ExportError: If the document cannot be built or serialised.
    """
    # Defensive sort
    chapters = sorted(chapters, key=lambda c: c.get("chapter_number", 0))
    try:
        doc = Document()

        # ── Title Page ──────────────────────────────────────────────────────
        title_para = doc.add_paragraph()
        title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = title_para.add_run(title)
        run.bold = True
        run.font.size = Pt(28)

        doc.add_paragraph()  # spacer

        subtitle_para = doc.add_paragraph()
        subtitle_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        subtitle_para.add_run("Generated by the Automated Book Generation System").italic = True

        doc.add_page_break()

        # ── Static Table of Contents ────────────────────────────────────────
        toc_heading = doc.add_heading("Table of Contents", level=1)
        toc_heading.alignment = WD_ALIGN_PARAGRAPH.LEFT

        for ch in chapters:
            toc_line = doc.add_paragraph(
                f"Chapter {ch['chapter_number']}: {ch['title']}"
            )
            toc_line.style = "List Number"

        doc.add_page_break()

        # ── Chapter Content ──────────────────────────────────────────────────
        for ch in chapters:
            chapter_heading = f"Chapter {ch['chapter_number']}: {ch['title']}"
            doc.add_heading(chapter_heading, level=1)

            # Split content on double-newlines → each block → one paragraph
            content: str = _clean_markdown(ch.get("content") or "")
            paragraphs = [p.strip() for p in content.split("\n\n") if p.strip()]
            for para_text in paragraphs:
                doc.add_paragraph(para_text)

            doc.add_page_break()

        # ── Serialise ────────────────────────────────────────────────────────
        buffer = io.BytesIO()
        doc.save(buffer)
        buffer.seek(0)
        raw_bytes = buffer.read()
        log.info("Built .docx: %d bytes, %d chapters.", len(raw_bytes), len(chapters))
        return raw_bytes

    except Exception as exc:
        raise ExportError(f"Failed to build .docx for '{title}': {exc}") from exc


# ── .txt Builder ──────────────────────────────────────────────────────────────

def build_txt(title: str, chapters: list[dict]) -> bytes:
    """
    Assemble a plain-text file: title header followed by each chapter.

    Args:
        title:    The book title.
        chapters: Same structure as for build_docx.
                  (Automatically sorted by chapter_number if not already).

    Returns:
        UTF-8 encoded bytes of the plain-text file.

    Raises:
        ExportError: If serialisation fails.
    """
    # Defensive sort
    chapters = sorted(chapters, key=lambda c: c.get("chapter_number", 0))
    try:
        lines: list[str] = []

        # Title banner
        separator = "=" * 60
        lines.append(separator)
        lines.append(title.upper())
        lines.append(separator)
        lines.append("")

        for ch in chapters:
            lines.append("")
            lines.append(f"CHAPTER {ch['chapter_number']}: {ch['title'].upper()}")
            lines.append("-" * 60)
            lines.append("")
            content: str = _clean_markdown(ch.get("content") or "")
            lines.append(content)
            lines.append("")

        text = "\n".join(lines)
        raw_bytes = text.encode("utf-8")
        log.info("Built .txt: %d bytes, %d chapters.", len(raw_bytes), len(chapters))
        return raw_bytes

    except Exception as exc:
        raise ExportError(f"Failed to build .txt for '{title}': {exc}") from exc


# ── Storage Path Helper ───────────────────────────────────────────────────────

def make_storage_path(book_id: str, title: str, extension: str) -> str:
    """
    Build the storage object path for a compiled book file.

    Convention: <book_id>/<sanitised_title>.<extension>

    Args:
        book_id:   UUID of the book record.
        title:     Book title (will be sanitised to be path-safe).
        extension: File extension without leading dot (e.g. "docx", "txt").

    Returns:
        A URL-safe storage path string.
    """
    safe_title = "".join(
        c if c.isalnum() or c in ("-", "_") else "_"
        for c in title.replace(" ", "_")
    )[:80]  # cap at 80 chars
    return f"{book_id}/{safe_title}.{extension}"
